### ISSUE TITLE
support for ros2 humble and gazebo_ros2_control

### ISSUE THREAD

**Issue by kei1107** [atinfinity/megarover_samples_ros2#7]
I have made megarover_samples_ros2 executable on ros2 humble using gazebo_ros2_control. In addition, there are other minor improvements.  
If you can create a humble branch from the main branch, we will do a PR on the hubmle branch.

<https://github.com/atinfinity/megarover_samples_ros2/compare/main...kei1107:megarover_samples_ros2:humble>

---

- Remove unused files and do gazebo spawn and `/robot_description` publishing from a single xacro file[75ac1850e7eee5d3a6b130b446816e7e82904f66...0cd32dcf3e7dcfee7be64d31bee4aa2cb4c87aee]
- Updated to allow use of either `libgazebo_diff_drive_controller.so` or `gazebo_ros2_control` via`use_ros2_control` option. [0cd32dcf3e7dcfee7be64d31bee4aa2cb4c87aee...f1883724f8792e6bd08dfa8dc94028e8a8666382] [787ac29b1b06726520ea03e0f3b02f3ee7836a22]
- Updated nav2 parameters for humble [db1fa89f00b80bd4e8e3a00b43486aa2445449f6] [efb9ec38aa723c1e1af78ae0e0536552ea275f60]
- Updated README for humble [03784276bbeb85d68b6a872ac30827b0f12b3220]

---

I tested on I tested on docker-ros2-desktop-vnc.  

```shell
docker run -p 6080:80 --shm-size=512m --security-opt seccomp=unconfined tiryoh/ros2-desktop-vnc:humble
```

The following commands can be used to switch execution methods.

**Use `libgazebo_diff_drive_controller.so`**

```shell
ros2 launch megarover_samples_ros2 vmegarover_with_sample_world.launch.py
```

**Use `gazebo_ros2_control`**

```shell
ros2 launch megarover_samples_ros2 vmegarover_with_sample_world.launch.py use_ros2_control:=true
```

**Comment by atinfinity** [comment]
Merged https://github.com/atinfinity/megarover_samples_ros2/pull/8. So, I closed this issue.
